project_id = "irrxmoqbgygyyzozifdl"

[functions.initialize-admission-payment]
verify_jwt = false

[functions.verify-admission-payment]
verify_jwt = false

[functions.initialize-acceptance-payment]
verify_jwt = false

[functions.verify-acceptance-payment]
verify_jwt = false

[functions.send-offer-letter]
verify_jwt = true

[functions.send-admission-notification]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.accept-offer]
verify_jwt = false

[functions.track-application]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false